http_client/lib/http_client_web/router.ex
defmodule HttpClientWeb.Router do
  use HttpClientWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/hangman", HttpClientWeb do
    pipe_through :browser # Use the default browser stack

    get "/", HangmanController, :new_game

    post "/", HangmanController, :create_game

    put "/", HangmanController, :make_move

  end

  # Other scopes may use custom stacks.
  # scope "/api", HttpClientWeb do
  #   pipe_through :api
  # end
end

http_client/lib/http_client/application.ex
defmodule HttpClient.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the endpoint when the application starts
      supervisor(HttpClientWeb.Endpoint, []),
      # Start your own worker by calling: HttpClient.Worker.start_link(arg1, arg2, arg3)
      # worker(HttpClient.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: HttpClient.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    HttpClientWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

http_client/lib/http_client_web/controllers/hangman_controller.ex
defmodule HttpClientWeb.HangmanController do
  use HttpClientWeb, :controller

  def new_game(conn, _params) do
    render conn, "new_game.html"
  end

  def create_game(conn, _params) do
    game = Hangman.new_game()
    tally = Hangman.tally(game)

    conn
    |> put_session(:game, game)
    |> render("game_field.html", tally: tally)
  end
end

http_client/lib/http_client_web/views/error_view.ex
defmodule HttpClientWeb.ErrorView do
  use HttpClientWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

http_client/lib/http_client_web/views/hangman_view.ex
defmodule HttpClientWeb.HangmanView do
  use HttpClientWeb, :view
end

http_client/lib/http_client_web/views/layout_view.ex
defmodule HttpClientWeb.LayoutView do
  use HttpClientWeb, :view
end

http_client/lib/http_client_web/templates/hangman/game_field.html.eex
<%= inspect @tally%>

<p>
    Turns left: <%= @tally.turns_left %>
</p>

<p>
    Word so far: <%= @tally.letters |> Enum.join(" ") %>
</p>

<%= form_for(@conn, hangman_path(@conn, :make_move), [ as: :make_move, method :put], fn f -> %>
    <%= text_input(f, :guess) %>
    <%= submit("Make next move") %>
<% end) %>

</form>

http_client/lib/http_client_web/templates/hangman/new_game.html.eex
<h1>Welcome to Hangman!</h1>

<%= button("New Game", to: hangman_path(@conn, :create_game)) %>

http_client/lib/http_client_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Hangman!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>